cd "C:\Users\jeremy.hervelin\Desktop\CH19"

use panel_generation, clear


label var generation "source de l'enquête génération"
label var ident "identifiant de l'individu"
label var pondef "poids national de l'individu"
label var date "date de la situation"
label var date_label "date de la situation en clair"
label var seq "ordre de la situation"
label var situation "situation de l'individu"
label var duree "durée de la situation"
label var femme "=1 si l'individu est une femme"
label var dep_residence "département de résidence à la date de l'enquête"
label var permis "=1 si l'individu a obtenu le permis au plus tard à la fin de la formation"
label var siblings "=1 si l'individu a au moins un frère ou une soeur"
label var langue_famille "=1 si la langue parlée dans la famille est le français"
label var pays_naissance_pere "pays de naissance du père"
label var nationalite_pere "=1 si le père est de nationalité française"
label var langue_pere "=1 si le père parle français"
label var emploi_pere "=1 si le père travaille à la fin des études"
label var niveau_pere "niveau d'étude du père selon la classification française"
label var pays_naissance_mere "pays de naissance de la mère"
label var nationalite_mere "=1 si la mère est de nationalité française"
label var langue_mere "=1 si la mère parle français"
label var emploi_mere "=1 si la mère travaille à la fin des études"
label var niveau_mere "niveau d'étude de la mère selon la classification française"
label var handicap "=1 si l'individu a un handicap déclanché avant la fin des études"
label var zone_commune "localisation de la zone d'habitation au moment de la 6è"
label var redoublement "=1 si l'individu a redoublé avant la 6è"
label var troisieme_generale "=1 si l'individu a fait une 3è générale"
label var premier_voeu "=1 si la formation après la 3è était le premier voeu"
label var bourse_college "=1 si l'individu a reçu une bourse sur critères sociaux au collège"
label var bourse_lycee "=1 si l'individu a reçu une bourse sur critères sociaux au lycée"
label var voyage_scolaire "=1 si l'individu a effectué un voyage scolaire durant sa scolarité"
label var region_etablissement "région de l'établissement de formation pendant le cap-bep"
label var apprentissage "=1 si l'individu a suivi sa formation par apprentissage"
label var centre_apprentissage "=1 si l'individu a suivi sa formation dans un centre de formation d'apprentis"
label var entreprise_apprentissage "personne qui a trouvé l'entreprise de formation en apprentissage"
label var depart_entr_apprentissage "=1 si l'individu a quitté l'entreprise avant la fin de son contrat"
label var tuteur_apprentissage "=1 si l'individu était sous la direction d'un tuteur d'apprentissage"
label var souhait_apprentissage "=1 si l'individu souhaitait faire sa formation en apprentissage"
label var raison_non_apprenti "raison pour laquelle l'individu n'a pas fait sa formation en apprentissage"
label var embauche_entr_appr "=1 si l'individu a été embauché par l'entreprise de formation à l'issu de son contrat"
label var embauche_tard_entr_appr "=1 si l'individu a travaillé pour son entreprise de formation plus tard qu'à la fin de son contrat"
label var specialite_naf10 "spécialité de la formation selon la nomenclature insee naf 10 des activités"
label var specialite_naf38 "spécialité de la formation selon la nomenclature insee naf 38 des activités"
label var diplome "=1 si l'individu a obtenu son cap ou bep"
label var age_sortie_formation "âge à la sortie de formation (en années)"
label var stages "=1 si l'individu a effectué un stage pendant sa formation"
label var nb_stages "nombre de stages effectués pendant la formation"
label var duree_travail_formation "durée (en mois) du dernier stage"
label var aide_stage "canal par lequel l'individu a trouvé son dernier stage"
label var obligation_stage "=1 si le dernier stage était obligatoire dans la formation"
label var stage_formation "=1 si le dernier stage est lié à la formation"
label var stage_premier_emploi "=1 si le dernier stage a débouché sur un premier emploi"
label var duree_pour_cdi "nombre de mois pour obtenir son premier cdi (vide si aucun cdi)"
label var duree_pour_emploi "nombre de mois pour obtenir un premier emploi"
label var temps_complet "=1 si le travail est à temps complet"
label var remuneration "rémunération mensuelle net du travail (en €)"
label var secteur_prive "=1 si l'individu travaille dans le secteur privé"
label var multi_etablissement "=1 si l'entreprise a plusieurs établissements"
label var taille_entreprise "taille de l'entreprise suivant son nombre de salariés"
label var travail_anterieur_entreprise "=1 si l'individu avait déjà travaillé dans l'entreprise"
label var type_travail_anterieur "type de travail si l'individu a déjà travaillé dans l'entreprise"
label var connaissance_salarie_entreprise "=1 si l'individu connaissant un salarié dans l'entreprise avant d'y travailler"
label var type_connaissance_salarie "canal via lequel l'individu connaissant le salarié dans l'entreprise"
label var connaissance_embauche "canal via lequel l'individu a pris connaissance de l'embauche dans l'entreprise"
label var formation_debut "=1 si l'individu a suivi une formation au début de sa prise de poste"
label var raison_depart "raison pour laquelle l'individu et l'entreprise se sont séparés"
label var motif_demission "raison pour laquelle l'individu a démissioné"
label var volonte_rester "=1 si l'individu souhaitait rester dans l'entrepris au moment de la séparation"
label var satisfait "=1 si l'individu s'estime satisfait de sa situation au moment de l'enquête"
label var optimisme "=1 si l'individu s'estime optimiste sur situation future au moment de l'enquête"
label var independant "=1 si l'individu envisage d'entreprendre une création d'entreprise au moment de l'enquête"
label var quitter_region "=1 si l'individu envisage de quitter sa région de résidence dans les cinq ans au moment de l'enquête"
label var changer_metier "=1 si l'individu envisage de changer de métier dans les cinq ans au moment de l'enquête"
label var discrimination "=1 si l'individu a connu des discriminations sur le marché du travail"
label var tx_chomage "taux de chômage trimestriel du département de résidence"
label var pcs "catégorie socio-professionnel du jeune à l'embauche"
label var naf "secteur d'activité de l'entreprise"
label var salaire_debut "salaire à l'embauche du jeune salarié"
label var salaire_fin "salaire à la fin du contrat du jeune salarié"


save, replace
